; [env:esp32doit-devkit-v1]
; platform = espressif32
; board = esp32doit-devkit-v1
; framework = arduino
; monitor_speed = 115200
; upload_speed = 921600

; build_flags = 
;     -std=gnu++17
;     -DI2C_BUFFER_LENGTH=128
;     -Wno-format-truncation
;     -Wno-sign-compare
;     -Wno-unused-variable
;     -DARDUINO_RUNNING_CORE=1

; lib_deps = 
;     sparkfun/SparkFun MAX3010x Pulse and Proximity Sensor Library
;     hideakitai/ArduinoEigen
;     adafruit/Adafruit SSD1306
;     adafruit/Adafruit GFX Library
;     tanakamasayuki/TensorFlowLite_ESP32

; platformio.ini (Arquivo de Configuração do Projeto)

[env:esp32doit-devkit-v1]
; Define um "ambiente" de construção. 
platform = espressif32
; Plataforma de hardware (família de chips ESP32)
board = esp32doit-devkit-v1
framework = arduino
; Estrutura (linguagem) Arduino
monitor_speed = 115200
; Velocidade da porta serial para o "Monitor Serial"
upload_speed = 921600
; Velocidade de upload do código para o ESP32 (mais rápida)

build_flags = 
    ; "Flags" (opções) para o compilador C++
    -std=gnu++17
    ; Habilita recursos modernos do C++ (como 'auto [a, b] = ...')
    -DI2C_BUFFER_LENGTH=128
    ; Aumenta o buffer do I2C (útil para o display e sensor)
    -Wno-format-truncation
    ; Desativa avisos de compilação específicos (limpeza)
    -Wno-sign-compare
    -Wno-unused-variable
    -DARDUINO_RUNNING_CORE=1
    ; Fixa a execução do código no Core 1 (boa prática no ESP32)

lib_deps = 
    ; Lista de bibliotecas que o PlatformIO deve baixar
    sparkfun/SparkFun MAX3010x Pulse and Proximity Sensor Library
    ; Biblioteca para o sensor MAX30102
    hideakitai/ArduinoEigen
    ; Biblioteca para operações de Álgebra Linear (matrizes/vetores)
    adafruit/Adafruit SSD1306
    ; Biblioteca para o display OLED SSD1306
    adafruit/Adafruit GFX Library
    ; Biblioteca gráfica (desenhar formas, texto) para o display
    tanakamasayuki/TensorFlowLite_ESP32
    ; Biblioteca principal do TensorFlow Lite para o ESP32